export 'package:components/src/screens/alert_screen.dart';
export 'package:components/src/screens/animeted_screen.dart';
export 'package:components/src/screens/avatar_screen.dart';
export 'package:components/src/screens/card_screen.dart';
export 'package:components/src/screens/Inputs_screen.dart';
export 'package:components/src/screens/home_screen.dart';
export 'package:components/src/screens/listview1_screen.dart';
export 'package:components/src/screens/listview2_screen.dart';
export 'package:components/src/screens/slider_screen.dart';